/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateProduitArgs } from "./CreateProduitArgs";
import { UpdateProduitArgs } from "./UpdateProduitArgs";
import { DeleteProduitArgs } from "./DeleteProduitArgs";
import { ProduitFindManyArgs } from "./ProduitFindManyArgs";
import { ProduitFindUniqueArgs } from "./ProduitFindUniqueArgs";
import { Produit } from "./Produit";
import { ProduitService } from "../produit.service";

@graphql.Resolver(() => Produit)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ProduitResolverBase {
  constructor(
    protected readonly service: ProduitService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Produit",
    action: "read",
    possession: "any",
  })
  async _produitsMeta(
    @graphql.Args() args: ProduitFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Produit])
  @nestAccessControl.UseRoles({
    resource: "Produit",
    action: "read",
    possession: "any",
  })
  async produits(
    @graphql.Args() args: ProduitFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Produit[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Produit",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Produit, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Produit",
    action: "read",
    possession: "own",
  })
  async produit(
    @graphql.Args() args: ProduitFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Produit | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Produit",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Produit)
  @nestAccessControl.UseRoles({
    resource: "Produit",
    action: "create",
    possession: "any",
  })
  async createProduit(
    @graphql.Args() args: CreateProduitArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Produit> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Produit",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Produit"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Produit)
  @nestAccessControl.UseRoles({
    resource: "Produit",
    action: "update",
    possession: "any",
  })
  async updateProduit(
    @graphql.Args() args: UpdateProduitArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Produit | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Produit",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Produit"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Produit)
  @nestAccessControl.UseRoles({
    resource: "Produit",
    action: "delete",
    possession: "any",
  })
  async deleteProduit(
    @graphql.Args() args: DeleteProduitArgs
  ): Promise<Produit | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
